---
stages:
  - linting

ansible-lint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint --show-relpath
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
