- name: Make gpg temp dir
  ansible.builtin.tempfile:
    state: "directory"
  register: gpg_tempdir

- name: Get Jellyfin GPG signing key
  ansible.builtin.get_url:
    url: "https://repo.jellyfin.org/jellyfin_team.gpg.key"
    dest: "{{ gpg_tempdir.path }}/jellyfin.asc"
    force: true
    mode: '0644'

- name: Dearmor Jellyfin GPG signing key
  ansible.builtin.shell: "gpg --dearmor -o {{ gpg_tempdir.path }}/jellyfin.gpg {{ gpg_tempdir.path }}/jellyfin.asc"

- name: Copy Jellyfin GPG sigining key to apt path
  ansible.builtin.copy:
    src: "{{ gpg_tempdir.path }}/jellyfin.gpg"
    dest: "/etc/apt/keyrings/jellyfin.gpg"
    remote_src: true
