---

- name: Install dependencies
  apt: 
    pkg:
      - gnupg

- name: Make dirs
  file:
    path:
    - "/etc/apt/keyrings"
    - "/etc/apt/sources.list.d"
    state: directory

- include_tasks:
    file: apt_gpg.yml

- name: Gather dpkg architecture info
  shell: "dpkg --print-architecture"
  register: dpkg_content
  changed_when: false

- name: Set system info
  set_fact:
    version_os: "{{ hostvars[inventory_hostname].ansible_distribution | lower }}"
    version_codename: "{{ hostvars[inventory_hostname].ansible_distribution_release | lower }}"
    arch: "{{ dpkg_content.stdout | lower }}"
  changed_when: false

# if ansible-core >= 2.15
#
# - name: Add Jellyfin repo
#   deb822_repository:
#     name: jellyfin
#     types: deb
#     uris: "https://repo.jellyfin.org/{{ version_os }}"
#     suites: "{{ version_codename }}"
#     components: main
#     architectures: "{{ arch }}"
#     signed_by: /etc/apt/trusted.gpg.d/jellyfin.pgp

- name: Add Jellyfin Repo
  template:
    src: "jellyfin.sources.jinja"
    dest: "/etc/apt/sources.list.d/jellyfin.sources"

- name: Install Jellyfin
  apt:
    pkg: "{{ item }}"
  loop:
    - "jellyfin-web"
    - "jellyfin-server"
  notify: Restart Jellyfin

- include_tasks: dirs.yml

- name: Make config
  include_tasks: config.yml
